[package]
name = "data-matrix"
version = "0.5.1"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
terminal_size = "0.1.17"
console_engine = "2.0.1"
clap = {version = "2.33.3", features = ["yaml"]}
rand = "0.8.3"